# # Resolve react_native_pods.rb with node to allow for hoisting
# require Pod::Executable.execute_command('node', ['-p',
#   'require.resolve(
#     "react-native/scripts/react_native_pods.rb",
#     {paths: [process.argv[1]]},
#   )', __dir__]).strip

# platform :ios, min_ios_version_supported
# # platform :ios, '11.0'
# prepare_react_native_project!

# linkage = ENV['USE_FRAMEWORKS']
# if linkage != nil
#   Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
#   use_frameworks! :linkage => linkage.to_sym
# end

# target 'PhotoApp' do
#   config = use_native_modules!
#   use_frameworks! :linkage => :static
#   $RNFirebaseAsStaticFramework = true
#   pod 'GoogleMaps'
#   pod 'GoogleMaps/Base'
#   pod 'GoogleMaps/Maps'
#   pod 'Firebase/Storage'
#   pod 'RNFBCrashlytics',
#   :path => '../node_modules/@react-native-firebase/crashlytics'

#   use_react_native!(
#     :path => config[:reactNativePath],
#     # An absolute path to your application root.
#     :app_path => "#{Pod::Config.instance.installation_root}/.."

#   )


#   target 'PhotoAppTests' do
#     inherit! :complete
#     # Pods for testing
#   end

#   post_install do |installer|
#     # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
#     react_native_post_install(
#       installer,
#       config[:reactNativePath],
#       :mac_catalyst_enabled => false,
#       # :ccache_enabled => true
#     )
#   end
# end


# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

# Specify the platform and minimum iOS version
platform :ios, '13.4'  # Ensure this matches your app's deployment target

prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'PhotoApp' do
  config = use_native_modules!

  # Use static frameworks for better compatibility with most RN libraries
  use_frameworks! :linkage => :static
  $RNFirebaseAsStaticFramework = true

  # Google Maps dependencies
  pod 'GoogleMaps'
  pod 'GoogleMaps/Base'
  pod 'GoogleMaps/Maps'

  # Firebase dependencies
  pod 'Firebase/Storage'
  pod 'RNFBCrashlytics',
      :path => '../node_modules/@react-native-firebase/crashlytics'

  # React Native setup
  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'PhotoAppTests' do
    inherit! :complete
    # Add any test-specific dependencies here if needed
  end

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
  end
end
